Repository mermaid-js/mermaid-cli, pull requests merged in 2021-11, with the labels that each got.

#187 Remove missing package libappindicator1
  install-dependencies.sh
Labels: chore

#189 Add optional CR to markdown graph detection regex.
  .gitattributes
  src/index.js
  test-positive/crlf-detect.md
Labels: fix

#199 Use ESM imports now
  src/index.js
Labels: feature
