Repository mermaid-js/mermaid-cli, pull requests merged in 2022-10, with the labels that each got.

#389 ci(test): fix convert-svg-to-png in mermaid 9.1.7
  run-tests.sh
  test-positive/config-noUseMaxWidth.json
Labels: hacktoberfest-accepted

#388 test(mermaid.md): cleanup mermaid.md test case
  src-test/test.js
  test-positive/mermaid.md
Labels: hacktoberfest-accepted

#387 feat: load title/desc text from Mermaid SVG
  README.md
  src-test/test.js
  src/index.js
  test-positive/mermaid.md
Labels: feature, hacktoberfest-accepted

#396 Discontinue brew support
  README.md
Labels: documentation, hacktoberfest-accepted

#399 Log mermaid puppeteer output to console.log
  docs/animated-flowchart.svg
Labels: hacktoberfest-accepted, fix

#407 Fixing typos
  .github/workflows/compile-mermaid.yml
  README.md
  docs/reviewing.md
Labels: hacktoberfest-accepted
