Repository mermaid-js/mermaid-cli, pull requests merged in 2022-08, with the labels that each got.

#350 Switch package to use ESM (removes `babel` requirement)
  .babelrc
  .github/workflows/release-publish.yml
  .github/workflows/test.yml
  DockerfileBuild
  building.md
  package.json
  src-test/test.js
  src/index.js
  yarn.lock
Labels: feature

#351 Support SVG/PDF template files for markdown input
  src-test/test.js
  src/index.js
Labels: fix

#365 Run yarn standard --fix
  src-test/test.js
  src/index.js
Labels: feature

#366 ci: fix percy CI upload from forks
  .github/workflows/compile-mermaid.yml
  .github/workflows/upload-percy.yml
Labels: github_actions

#367 docs: document `--cssFile` option in README
  README.md
  docs/animated-flowchart.svg
  src-test/test.js
  test-positive/config-deterministic.json
  test-positive/flowchart1.css
Labels: documentation
